export const countries = [
  {
    name: 'Brasil',
    capital: 'Brasília',
    continent: 'América do Sul',
    population: 203080756,
    flag: '🇧🇷',
    language: 'Português',
  },
  {
    name: 'Japão',
    capital: 'Tóquio',
    continent: 'Ásia',
    population: 123890000,
    flag: '🇯🇵',
    language: 'Japonês',
  },
  {
    name: 'Canadá',
    capital: 'Ottawa',
    continent: 'América do Norte',
    population: 41012600,
    flag: '🇨🇦',
    language: 'Inglês e francês',
  },
  {
    name: 'Portugal',
    capital: 'Lisboa',
    continent: 'Europa',
    population: 10640000,
    flag: '🇵🇹',
    language: 'Português',
  },
  {
    name: 'Ucrânia',
    capital: 'Kyiv',
    continent: 'Europa',
    population: 37900000,
    flag: '🇺🇦',
    language: 'Ucraniano',
  },
  {
    name: 'Argentina',
    capital: 'Buenos Aires',
    continent: 'América do Sul',
    population: 45810000,
    flag: '🇦🇷',
    language: 'Espanhol',
  },
  {
    name: 'Índia',
    capital: 'Nova Délhi',
    continent: 'Ásia',
    population: 1463900000,
    flag: '🇮🇳',
    language: 'Hindi e inglês',
  },
  {
    name: 'Quênia',
    capital: 'Nairóbi',
    continent: 'África',
    population: 52428290,
    flag: '🇰🇪',
    language: 'Suaíli e inglês',
  },
  {
    name: 'Austrália',
    capital: 'Camberra',
    continent: 'Oceania',
    population: 27297000,
    flag: '🇦🇺',
    language: 'Inglês',
  },
];
